version: '3'

services:
  server1-container:
    build:
      context: .
      dockerfile: Dockerfile-server1
    # ports:
    #   - "7100:4567"
    scale: 3
    networks:
      - alpine-net
    # container_name: server1-container
    command: ["python", "-u", "Server1.py"]
    depends_on:
      - coordinate-service



  server2-container:
    build:
      context: .
      dockerfile: Dockerfile-server2
    # ports:
    #   - "7106:5372"
    scale: 3
    networks:
      - alpine-net
    # container_name: server2-container
    command: ["python", "-u", "Server2.py"]
    depends_on:
      - coordinate-service

  coordinate-service:
    build:
      context: .
      dockerfile: Dockerfile-coordinate
    ports:
      - "7108:8080"
    networks:
      - alpine-net
    container_name: coordinate-container
    command: ["python", "-u", "Server3.py"]
  
  message-broker:
    build:
      context: .
      dockerfile: Dockerfile-message-brocker
    ports:
      - "8090:8090"
    networks:
      - alpine-net
    container_name: message-brocker-container
    command: ["python", "-u", "Server4.py"]
    depends_on:
      - coordinate-service

networks:
  alpine-net:
    driver: bridge

